/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CheckoutSessionResponseDto,
  CreateCheckoutSessionDto,
  ErrorResponseDto,
} from '../models/index';
import {
    CheckoutSessionResponseDtoFromJSON,
    CheckoutSessionResponseDtoToJSON,
    CreateCheckoutSessionDtoFromJSON,
    CreateCheckoutSessionDtoToJSON,
    ErrorResponseDtoFromJSON,
    ErrorResponseDtoToJSON,
} from '../models/index';

export interface CreateCheckoutSessionRequest {
    createCheckoutSessionDto: CreateCheckoutSessionDto;
}

export interface ListAllCheckoutSessionsInternalRequest {
    merchantId: string;
    limit?: number;
    offset?: number;
}

export interface RetrieveCheckoutSessionInternalRequest {
    id: string;
}

/**
 * 
 */
export class CheckoutsApi extends runtime.BaseAPI {

    /**
     * Creates a hosted payment page. Used for: (1) A standard e-commerce purchase, or (2) a \"Pay-In\" to fund a CustomerBalance.
     * Create Hosted Checkout
     */
    async createCheckoutSessionRaw(requestParameters: CreateCheckoutSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckoutSessionResponseDto>> {
        if (requestParameters['createCheckoutSessionDto'] == null) {
            throw new runtime.RequiredError(
                'createCheckoutSessionDto',
                'Required parameter "createCheckoutSessionDto" was null or undefined when calling createCheckoutSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/checkout/sessions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCheckoutSessionDtoToJSON(requestParameters['createCheckoutSessionDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckoutSessionResponseDtoFromJSON(jsonValue));
    }

    /**
     * Creates a hosted payment page. Used for: (1) A standard e-commerce purchase, or (2) a \"Pay-In\" to fund a CustomerBalance.
     * Create Hosted Checkout
     */
    async createCheckoutSession(createCheckoutSessionDto: CreateCheckoutSessionDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckoutSessionResponseDto> {
        const response = await this.createCheckoutSessionRaw({ createCheckoutSessionDto: createCheckoutSessionDto }, initOverrides);
        return await response.value();
    }

    /**
     * Lists all checkout sessions across all merchants (internal use only)
     * List All Checkout Sessions
     */
    async listAllCheckoutSessionsInternalRaw(requestParameters: ListAllCheckoutSessionsInternalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CheckoutSessionResponseDto>>> {
        if (requestParameters['merchantId'] == null) {
            throw new runtime.RequiredError(
                'merchantId',
                'Required parameter "merchantId" was null or undefined when calling listAllCheckoutSessionsInternal().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['merchantId'] != null) {
            queryParameters['merchantId'] = requestParameters['merchantId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/checkout/sessions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CheckoutSessionResponseDtoFromJSON));
    }

    /**
     * Lists all checkout sessions across all merchants (internal use only)
     * List All Checkout Sessions
     */
    async listAllCheckoutSessionsInternal(merchantId: string, limit?: number, offset?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CheckoutSessionResponseDto>> {
        const response = await this.listAllCheckoutSessionsInternalRaw({ merchantId: merchantId, limit: limit, offset: offset }, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves details of a specific checkout session
     * Retrieve Checkout Session
     */
    async retrieveCheckoutSessionInternalRaw(requestParameters: RetrieveCheckoutSessionInternalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckoutSessionResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling retrieveCheckoutSessionInternal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/checkout/sessions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckoutSessionResponseDtoFromJSON(jsonValue));
    }

    /**
     * Retrieves details of a specific checkout session
     * Retrieve Checkout Session
     */
    async retrieveCheckoutSessionInternal(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckoutSessionResponseDto> {
        const response = await this.retrieveCheckoutSessionInternalRaw({ id: id }, initOverrides);
        return await response.value();
    }

}
