/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateOrganizationKycDto,
  ErrorResponseDto,
  OrganizationKycResponseDto,
  UpdateOrganizationKycDto,
} from '../models/index';
import {
    CreateOrganizationKycDtoFromJSON,
    CreateOrganizationKycDtoToJSON,
    ErrorResponseDtoFromJSON,
    ErrorResponseDtoToJSON,
    OrganizationKycResponseDtoFromJSON,
    OrganizationKycResponseDtoToJSON,
    UpdateOrganizationKycDtoFromJSON,
    UpdateOrganizationKycDtoToJSON,
} from '../models/index';

export interface CreateKycRequest {
    createOrganizationKycDto: CreateOrganizationKycDto;
}

export interface GetKycRequest {
    organizationId: string;
}

export interface UpdateKycRequest {
    id: string;
    updateOrganizationKycDto: UpdateOrganizationKycDto;
}

/**
 * 
 */
export class KYCApi extends runtime.BaseAPI {

    /**
     * Create KYC info
     */
    async createKycRaw(requestParameters: CreateKycRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationKycResponseDto>> {
        if (requestParameters['createOrganizationKycDto'] == null) {
            throw new runtime.RequiredError(
                'createOrganizationKycDto',
                'Required parameter "createOrganizationKycDto" was null or undefined when calling createKyc().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/kyc`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrganizationKycDtoToJSON(requestParameters['createOrganizationKycDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationKycResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create KYC info
     */
    async createKyc(createOrganizationKycDto: CreateOrganizationKycDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationKycResponseDto> {
        const response = await this.createKycRaw({ createOrganizationKycDto: createOrganizationKycDto }, initOverrides);
        return await response.value();
    }

    /**
     * Get KYC info for organization
     */
    async getKycRaw(requestParameters: GetKycRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationKycResponseDto>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling getKyc().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['organizationId'] != null) {
            queryParameters['organizationId'] = requestParameters['organizationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/kyc`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationKycResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get KYC info for organization
     */
    async getKyc(organizationId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationKycResponseDto> {
        const response = await this.getKycRaw({ organizationId: organizationId }, initOverrides);
        return await response.value();
    }

    /**
     * Update KYC info
     */
    async updateKycRaw(requestParameters: UpdateKycRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateKyc().'
            );
        }

        if (requestParameters['updateOrganizationKycDto'] == null) {
            throw new runtime.RequiredError(
                'updateOrganizationKycDto',
                'Required parameter "updateOrganizationKycDto" was null or undefined when calling updateKyc().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/canary/kyc/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrganizationKycDtoToJSON(requestParameters['updateOrganizationKycDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update KYC info
     */
    async updateKyc(id: string, updateOrganizationKycDto: UpdateOrganizationKycDto, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateKycRaw({ id: id, updateOrganizationKycDto: updateOrganizationKycDto }, initOverrides);
    }

}
