/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Organization } from './Organization';
import {
    OrganizationFromJSON,
    OrganizationFromJSONTyped,
    OrganizationToJSON,
    OrganizationToJSONTyped,
} from './Organization';

/**
 * 
 * @export
 * @interface ListOrganizationsResponseDto
 */
export interface ListOrganizationsResponseDto {
    /**
     * List of organizations
     * @type {Array<Organization>}
     * @memberof ListOrganizationsResponseDto
     */
    organizations: Array<Organization>;
}

/**
 * Check if a given object implements the ListOrganizationsResponseDto interface.
 */
export function instanceOfListOrganizationsResponseDto(value: object): value is ListOrganizationsResponseDto {
    if (!('organizations' in value) || value['organizations'] === undefined) return false;
    return true;
}

export function ListOrganizationsResponseDtoFromJSON(json: any): ListOrganizationsResponseDto {
    return ListOrganizationsResponseDtoFromJSONTyped(json, false);
}

export function ListOrganizationsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrganizationsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'organizations': ((json['organizations'] as Array<any>).map(OrganizationFromJSON)),
    };
}

export function ListOrganizationsResponseDtoToJSON(json: any): ListOrganizationsResponseDto {
    return ListOrganizationsResponseDtoToJSONTyped(json, false);
}

export function ListOrganizationsResponseDtoToJSONTyped(value?: ListOrganizationsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organizations': ((value['organizations'] as Array<any>).map(OrganizationToJSON)),
    };
}

