/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationResponseDto } from './PaginationResponseDto';
import {
    PaginationResponseDtoFromJSON,
    PaginationResponseDtoFromJSONTyped,
    PaginationResponseDtoToJSON,
    PaginationResponseDtoToJSONTyped,
} from './PaginationResponseDto';
import type { OrganizationKycResponseDto } from './OrganizationKycResponseDto';
import {
    OrganizationKycResponseDtoFromJSON,
    OrganizationKycResponseDtoFromJSONTyped,
    OrganizationKycResponseDtoToJSON,
    OrganizationKycResponseDtoToJSONTyped,
} from './OrganizationKycResponseDto';

/**
 * 
 * @export
 * @interface ListOrganizationKycResponseDto
 */
export interface ListOrganizationKycResponseDto {
    /**
     * 
     * @type {Array<OrganizationKycResponseDto>}
     * @memberof ListOrganizationKycResponseDto
     */
    data: Array<OrganizationKycResponseDto>;
    /**
     * 
     * @type {PaginationResponseDto}
     * @memberof ListOrganizationKycResponseDto
     */
    pagination: PaginationResponseDto;
}

/**
 * Check if a given object implements the ListOrganizationKycResponseDto interface.
 */
export function instanceOfListOrganizationKycResponseDto(value: object): value is ListOrganizationKycResponseDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListOrganizationKycResponseDtoFromJSON(json: any): ListOrganizationKycResponseDto {
    return ListOrganizationKycResponseDtoFromJSONTyped(json, false);
}

export function ListOrganizationKycResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrganizationKycResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(OrganizationKycResponseDtoFromJSON)),
        'pagination': PaginationResponseDtoFromJSON(json['pagination']),
    };
}

export function ListOrganizationKycResponseDtoToJSON(json: any): ListOrganizationKycResponseDto {
    return ListOrganizationKycResponseDtoToJSONTyped(json, false);
}

export function ListOrganizationKycResponseDtoToJSONTyped(value?: ListOrganizationKycResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(OrganizationKycResponseDtoToJSON)),
        'pagination': PaginationResponseDtoToJSON(value['pagination']),
    };
}

