/* tslint:disable */
/* eslint-disable */
/**
 * Cashful API
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cashful.africa
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationKycResponseDto
 */
export interface OrganizationKycResponseDto {
    /**
     * Unique identifier
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationKycResponseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationKycResponseDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationKycResponseDto
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    idNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    companyRegistrationName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    companyRegistrationNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    companyTradingName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    vatRegistrationNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    industry?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    subIndustry?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    estimatedAnnualTurnover?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    businessDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    companyEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    companyContactNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    socialMedia?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    accountContactNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    customerSupportContactNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    customerSupportEscalationContactNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    emergencyContactNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    streetAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    apartment?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    suburb?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    bank?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    accountType?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    accountName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    accountNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    branchCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationKycResponseDto
     */
    isSouthAfricanResidentAccount?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    certificateOfIncorporation?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    identityDocuments?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    bankAccountConfirmationLetter?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    proofOfBusinessAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    ecnsLicense?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationKycResponseDto
     */
    termsAccepted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationKycResponseDto
     */
    acceptedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof OrganizationKycResponseDto
     */
    currentStep?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationKycResponseDto
     */
    isCompleted?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OrganizationKycResponseDto
     */
    completionScore?: number;
}

/**
 * Check if a given object implements the OrganizationKycResponseDto interface.
 */
export function instanceOfOrganizationKycResponseDto(value: object): value is OrganizationKycResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    return true;
}

export function OrganizationKycResponseDtoFromJSON(json: any): OrganizationKycResponseDto {
    return OrganizationKycResponseDtoFromJSONTyped(json, false);
}

export function OrganizationKycResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationKycResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'organizationId': json['organizationId'],
        'idNumber': json['idNumber'] == null ? undefined : json['idNumber'],
        'companyRegistrationName': json['companyRegistrationName'] == null ? undefined : json['companyRegistrationName'],
        'companyRegistrationNumber': json['companyRegistrationNumber'] == null ? undefined : json['companyRegistrationNumber'],
        'companyTradingName': json['companyTradingName'] == null ? undefined : json['companyTradingName'],
        'vatRegistrationNumber': json['vatRegistrationNumber'] == null ? undefined : json['vatRegistrationNumber'],
        'industry': json['industry'] == null ? undefined : json['industry'],
        'subIndustry': json['subIndustry'] == null ? undefined : json['subIndustry'],
        'estimatedAnnualTurnover': json['estimatedAnnualTurnover'] == null ? undefined : json['estimatedAnnualTurnover'],
        'businessDescription': json['businessDescription'] == null ? undefined : json['businessDescription'],
        'companyEmail': json['companyEmail'] == null ? undefined : json['companyEmail'],
        'companyContactNumber': json['companyContactNumber'] == null ? undefined : json['companyContactNumber'],
        'website': json['website'] == null ? undefined : json['website'],
        'socialMedia': json['socialMedia'] == null ? undefined : json['socialMedia'],
        'accountContactNumber': json['accountContactNumber'] == null ? undefined : json['accountContactNumber'],
        'customerSupportContactNumber': json['customerSupportContactNumber'] == null ? undefined : json['customerSupportContactNumber'],
        'customerSupportEscalationContactNumber': json['customerSupportEscalationContactNumber'] == null ? undefined : json['customerSupportEscalationContactNumber'],
        'emergencyContactNumber': json['emergencyContactNumber'] == null ? undefined : json['emergencyContactNumber'],
        'streetAddress': json['streetAddress'] == null ? undefined : json['streetAddress'],
        'apartment': json['apartment'] == null ? undefined : json['apartment'],
        'suburb': json['suburb'] == null ? undefined : json['suburb'],
        'city': json['city'] == null ? undefined : json['city'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
        'bank': json['bank'] == null ? undefined : json['bank'],
        'accountType': json['accountType'] == null ? undefined : json['accountType'],
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'accountNumber': json['accountNumber'] == null ? undefined : json['accountNumber'],
        'branchCode': json['branchCode'] == null ? undefined : json['branchCode'],
        'isSouthAfricanResidentAccount': json['isSouthAfricanResidentAccount'] == null ? undefined : json['isSouthAfricanResidentAccount'],
        'certificateOfIncorporation': json['certificateOfIncorporation'] == null ? undefined : json['certificateOfIncorporation'],
        'identityDocuments': json['identityDocuments'] == null ? undefined : json['identityDocuments'],
        'bankAccountConfirmationLetter': json['bankAccountConfirmationLetter'] == null ? undefined : json['bankAccountConfirmationLetter'],
        'proofOfBusinessAddress': json['proofOfBusinessAddress'] == null ? undefined : json['proofOfBusinessAddress'],
        'ecnsLicense': json['ecnsLicense'] == null ? undefined : json['ecnsLicense'],
        'termsAccepted': json['termsAccepted'] == null ? undefined : json['termsAccepted'],
        'acceptedAt': json['acceptedAt'] == null ? undefined : (new Date(json['acceptedAt'])),
        'currentStep': json['currentStep'] == null ? undefined : json['currentStep'],
        'isCompleted': json['isCompleted'] == null ? undefined : json['isCompleted'],
        'completionScore': json['completionScore'] == null ? undefined : json['completionScore'],
    };
}

export function OrganizationKycResponseDtoToJSON(json: any): OrganizationKycResponseDto {
    return OrganizationKycResponseDtoToJSONTyped(json, false);
}

export function OrganizationKycResponseDtoToJSONTyped(value?: OrganizationKycResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'deletedAt': value['deletedAt'] == null ? value['deletedAt'] : value['deletedAt'].toISOString(),
        'organizationId': value['organizationId'],
        'idNumber': value['idNumber'],
        'companyRegistrationName': value['companyRegistrationName'],
        'companyRegistrationNumber': value['companyRegistrationNumber'],
        'companyTradingName': value['companyTradingName'],
        'vatRegistrationNumber': value['vatRegistrationNumber'],
        'industry': value['industry'],
        'subIndustry': value['subIndustry'],
        'estimatedAnnualTurnover': value['estimatedAnnualTurnover'],
        'businessDescription': value['businessDescription'],
        'companyEmail': value['companyEmail'],
        'companyContactNumber': value['companyContactNumber'],
        'website': value['website'],
        'socialMedia': value['socialMedia'],
        'accountContactNumber': value['accountContactNumber'],
        'customerSupportContactNumber': value['customerSupportContactNumber'],
        'customerSupportEscalationContactNumber': value['customerSupportEscalationContactNumber'],
        'emergencyContactNumber': value['emergencyContactNumber'],
        'streetAddress': value['streetAddress'],
        'apartment': value['apartment'],
        'suburb': value['suburb'],
        'city': value['city'],
        'postalCode': value['postalCode'],
        'bank': value['bank'],
        'accountType': value['accountType'],
        'accountName': value['accountName'],
        'accountNumber': value['accountNumber'],
        'branchCode': value['branchCode'],
        'isSouthAfricanResidentAccount': value['isSouthAfricanResidentAccount'],
        'certificateOfIncorporation': value['certificateOfIncorporation'],
        'identityDocuments': value['identityDocuments'],
        'bankAccountConfirmationLetter': value['bankAccountConfirmationLetter'],
        'proofOfBusinessAddress': value['proofOfBusinessAddress'],
        'ecnsLicense': value['ecnsLicense'],
        'termsAccepted': value['termsAccepted'],
        'acceptedAt': value['acceptedAt'] == null ? value['acceptedAt'] : value['acceptedAt'].toISOString(),
        'currentStep': value['currentStep'],
        'isCompleted': value['isCompleted'],
        'completionScore': value['completionScore'],
    };
}

